
Aborted!
Traceback (most recent call last):
  File "/Users/mwvaughn/src/cfn3/.env/lib/python3.12/site-packages/metaflow/multicore_utils.py", line 65, in _spawn
    ret = func(arg)
          ^^^^^^^^^
  File "/Users/mwvaughn/src/cfn3/.env/lib/python3.12/site-packages/metaflow/multicore_utils.py", line 170, in wrapper
    return idx, func(arg)
                ^^^^^^^^^
  File "/Users/mwvaughn/src/cfn3/.env/lib/python3.12/site-packages/metaflow/plugins/datatools/s3/s3op.py", line 556, in op_list_prefix_nonrecursive
    return [s3.list_prefix(prefix, delimiter="/") for prefix in prefix_urls]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mwvaughn/src/cfn3/.env/lib/python3.12/site-packages/metaflow/plugins/datatools/s3/s3util.py", line 41, in retry_wrapper
    ret = f(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mwvaughn/src/cfn3/.env/lib/python3.12/site-packages/metaflow/plugins/datatools/s3/s3op.py", line 493, in list_prefix
    self.reset_client()
  File "/Users/mwvaughn/src/cfn3/.env/lib/python3.12/site-packages/metaflow/plugins/datatools/s3/s3op.py", line 450, in reset_client
    self.s3, self.client_error = get_s3_client(
                                 ^^^^^^^^^^^^^^
  File "/Users/mwvaughn/src/cfn3/.env/lib/python3.12/site-packages/metaflow/plugins/datatools/s3/s3util.py", line 26, in get_s3_client
    return get_aws_client(
           ^^^^^^^^^^^^^^^
  File "/Users/mwvaughn/src/cfn3/.env/lib/python3.12/site-packages/metaflow/plugins/aws/aws_client.py", line 103, in get_aws_client
    return cached_provider_class.get_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mwvaughn/src/cfn3/.env/lib/python3.12/site-packages/metaflow/plugins/aws/aws_client.py", line 83, in get_client
    return session.client(module, **client_params), ClientError
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mwvaughn/src/cfn3/.env/lib/python3.12/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mwvaughn/src/cfn3/.env/lib/python3.12/site-packages/botocore/session.py", line 951, in create_client
    credentials = self.get_credentials()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mwvaughn/src/cfn3/.env/lib/python3.12/site-packages/botocore/session.py", line 509, in get_credentials
    ).load_credentials()
      ^^^^^^^^^^^^^^^^^^
  File "/Users/mwvaughn/src/cfn3/.env/lib/python3.12/site-packages/botocore/credentials.py", line 2038, in load_credentials
    creds = provider.load()
            ^^^^^^^^^^^^^^^
  File "/Users/mwvaughn/src/cfn3/.env/lib/python3.12/site-packages/botocore/credentials.py", line 976, in load
    creds_dict = self._retrieve_credentials_using(credential_process)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mwvaughn/src/cfn3/.env/lib/python3.12/site-packages/botocore/credentials.py", line 998, in _retrieve_credentials_using
    stdout, stderr = p.communicate()
                     ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 2115, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/lib/python3.12/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
